steps:
  - name: ":rspec:"
    command: "scripts/ci/setup.sh && scripts/ci/parallel_specs.sh"
    parallelism: 5
    plugins:
      - docker#v2.0.0:
        image: "ruby:2.7.2"
        workdir: /app
        env:
          - KNAPSACK_GENERATE_REPORT=true
