name: Lint
on: [pull_request, pull_request_review_comment]
jobs:
  cancel-previous-skunk:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Skunk
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
  skunk:
    runs-on: ubuntu-latest
    needs: [cancel-previous-skunk]
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Run Skunk
        run: |
          gem install skunk
          CURRENT_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
          echo "Executing on branch: $CURRENT_BRANCH"
          if [[ "$CURRENT_BRANCH" == "master" ]]; then
            skunk
          else
            skunk -b master
          fi

