name: Lint
on: [pull_request, pull_request_review_comment]

jobs:
  skunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Run Skunk
        run: |
          gem install skunk
          bundle exec skunk